---
- name: Install Spring
  hosts: all

  tasks:
  - name: Install prerequisites
    package:
      name:
      - vim
      - wget
      - git
      state: present

  - name: Pull Repo
    git:
      repo: "{{ petclinic_repo }}"
      version: "{{ petclinic_branch }}"
      dest: /var/www/springpetclinc/    

  - name: Install Java
    yum:
      name: "java-1.8.0-openjdk"
      state: latest  
    become: true
  
  - name: Install mvnw
    yum:
      name: "maven"
      state: latest  
    become: true
  
  - name: Start mvnw
    shell: "./mvnw package /var/www/springpetclinc/ &"

  - name: Start java
    shell: "nohup java -jar spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar /var/www/springpetclinc/target &"
