---
- hosts: all

  tasks:
  - name: Start Spring Pet Clinic 
    command: ./mvnw package
    args:
      chdir: /var/www/springpetclinc/
  - name: Start Spring Pet Clinic Java
    command: nohup java -jar app.jar &
    args:
      chdir: /var/www/springpetclinc/target
