---
- hosts: all

  tasks:
  - name: Start Spring Pet Clinic 
    shell: "./mvnw package /var/www/springpetclinc/ &"
    
  - name: Start Spring Pet Clinic Java
    shell: "nohup java -jar app.jar /var/www/springpetclinc/target &"